roulette:
  message: |+
    Hi <@{USER1}> and <@{USER2}>!

    Congratulations, you got lucky and the coffee matcher chose you. Now schedule some time to have a chat!

    Enjoy getting to know each other.

    (If you want to opt out from future DMs, just leave <#{CHANNEL_NAME}>)
